### ISSUE TITLE
app icon conflict

### ISSUE THREAD

**Issue by ff0o0** [RomainPiel/Shimmer-android#20]
android:icon="@drawable/ic_launcher"

My app icon turns into 'ic_launcher.png' of the shimmer library on Nexus 5(Android 5.1).But on the other phones Android 4.+ it's my 'ic_launcher.png'. How to fix ? change my icon file name ?

**Comment by frostymarvelous** [comment]
But the library doesn't have a launcher Icon.

**Comment by RomainPiel** [comment]
that error should have been solved in version 1.3.0 Please use version 1.4.0 and it should fix it. I noticed I didn't update the README with that info.

**Comment by RomainPiel** [comment]
oh and it looks like 1.4.0 has not been correctly been released, looking at it...

**Comment by frostymarvelous** [comment]
I don't know if this will work, but it should. 

Create hdpi mdpi xhdpi and xhdpi versions of your icon.  Or simply copy the original into these dues. It should override the lib.

**Comment by RomainPiel** [comment]
or just update the lib to 1.4.0

**Comment by ff0o0** [comment]
@frostymarvelous yes, i have different size icon.

@RomainPiel  updated, it not work. Does the library have the dir named 'drawable-hdpi-v4' ?

![45](https://cloud.githubusercontent.com/assets/6087047/7150730/abfc0492-e351-11e4-91e2-713e07f42702.png)

**Comment by ff0o0** [comment]
i have solved by adding dir named 'drawable-xxhdpi'.

**Comment by claust** [comment]
As ff0o0 pointed out, this issue seems to remain in the 1.4.0 available from the mvn repo.
@RomainPiel Any chance the repo has not been updated properly? The date says Jan 12th 2015: http://mvnrepository.com/artifact/com.romainpiel.shimmer/library/1.4.0
